[project]
name = "artbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "leandro", email = "leandroep10@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "faster-whisper>=1.2.1",
    "llama-cpp-python>=0.3.35",
    "numpy>=2.5.3",
    "piper-tts>=1.8.0",
    "pvporcupine>=4.0.0",
    "python-dotenv>=1.0.0",
    "sounddevice>=0.5.6",
    "setuptools<81",
    "webrtcvad>=2.0.10",
    "openwakeword>=0.4.0",
]

[project.scripts]
artbot = "artbot.main:main"

[tool.uv]
no-binary-package = ["llama-cpp-python"]

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
namespace = true
